apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
nameSuffix: -backend
commonLabels:
  role: backend
  app: podinfo-backend
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podinfo
  spec:
    template:
      spec:
        containers:
        - name: podinfod
          env:
          - name: PODINFO_OTEL_SERVICE_NAME
            value: podinfo-backend
